const thumbnailSize = '200x200';
const distPath = '/assets/images/';
const projectsPath = `${distPath}projects/`;

export const projects = [
	{
		id: 31,
		image: `${projectsPath}2026-04-10-pixelated.jpg`,
		thumb: `${projectsPath}2026-04-10-pixelated-${thumbnailSize}.jpg`,
		name: 'Pixelated',
		date: '04.10.26',
		technologies: 'React, TypeScript, JavaScript, CSS, Sass, HTML, Vite, Immer, TanStack Query, ESLint, Prettier',
		categories: 'Personal',
		description: `A pixel "art" guessing game.`,
		url: '//pixelated.display.coffee',
	},
	{
		id: 30,
		image: `${projectsPath}2023-09-14-displaycoffee.jpg`,
		thumb: `${projectsPath}2023-09-14-displaycoffee-${thumbnailSize}.jpg`,
		name: 'Portfolio',
		name2: 'Portfolio 4',
		date: '09.14.23',
		technologies: 'React, TypeScript, JavaScript, CSS, Sass, HTML, Vite, ESLint, Prettier',
		categories: 'Personal',
		description: `The latest version of my portfolio. You're on it.`,
	},
	{
		id: 29,
		image: `${projectsPath}2022-06-25-ff7-for-st-jude.jpg`,
		thumb: `${projectsPath}2022-06-25-ff7-for-st-jude-${thumbnailSize}.jpg`,
		name: 'FF7 for St. Jude',
		date: '06.25.22',
		technologies: 'React, TypeScript, JavaScript, CSS, Sass, HTML, Vite, TanStack Query, ESLint, Prettier, Tiltify API',
		categories: 'Gaming',
		description: `Since December 28, 2020, my husband began a charity Final Fantasy VII speedrun event to support St. Jude. We have done this event twice a year since then. I get to help him out a little and specifically made this page using the Tiltify API to pull in donations, challenges, and rewards for all supporting campaigns. Right now, it's not fully working, but it'll be up and running for the next event.`,
		url: '//ff7forstjude.org',
	},
	{
		id: 28,
		image: `${projectsPath}2019-01-13-khyeras.jpg`,
		thumb: `${projectsPath}2019-01-13-khyeras-${thumbnailSize}.jpg`,
		name: `Khy'eras`,
		name2: `Khy'eras 2`,
		date: '01.13.19',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, phpBB',
		categories: 'Gaming',
		description: `This was a lighter theme I made for Khy'eras. You can only see it if registered. It shares the same code base as the dark layout, but basically changes CSS and images.`,
		url: '//khyeras.org',
	},
	{
		id: 27,
		image: `${projectsPath}2017-06-11-khyeras.jpg`,
		thumb: `${projectsPath}2017-06-11-khyeras-${thumbnailSize}.jpg`,
		name: `Khy'eras`,
		date: '06.11.17',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, phpBB',
		categories: 'Gaming',
		description: `Website for my latest RPG, Khy'eras. I'm quite proud of this one, not just for the coding customizations, but for all the lore I put together.`,
		url: '//khyeras.org',
	},
	{
		id: 26,
		image: `${projectsPath}2016-09-12-muses-circle.jpg`,
		thumb: `${projectsPath}2016-09-12-muses-circle-${thumbnailSize}.jpg`,
		name: 'The Muses Circle',
		name2: 'The Muses Circle 2',
		date: '09.12.16',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, WordPress',
		categories: 'Journal',
		description: `Second website layout for The Muses Circle. Currently not up, but we hope to bring it back in the future.`,
	},
	{
		id: 25,
		image: `${projectsPath}2014-02-22-aleris.jpg`,
		thumb: `${projectsPath}2014-02-22-aleris-${thumbnailSize}.jpg`,
		name: 'Aleris',
		name2: 'Aleris 5',
		date: '02.22.14',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, phpBB',
		categories: 'Gaming',
		description: `My final website layout for Aleris before I shut it down. This is still one of my favorites and I really loved the foliage drooping over the brick wall.`,
	},
	{
		id: 24,
		image: `${projectsPath}2013-12-16-aleris.jpg`,
		thumb: `${projectsPath}2013-12-16-aleris-${thumbnailSize}.jpg`,
		name: 'Aleris',
		name2: 'Aleris 4',
		date: '12.16.13',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, phpBB',
		categories: 'Gaming',
		description: `This came shortly after the previous layout and was a kind of darker version of the previous mockup. I do like the textured gradient here, but did not end up using it.`,
	},
	{
		id: 23,
		image: `${projectsPath}2013-10-10-aleris.jpg`,
		thumb: `${projectsPath}2013-10-10-aleris-${thumbnailSize}.jpg`,
		name: 'Aleris',
		name2: 'Aleris 3',
		date: '10.10.13',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, phpBB',
		categories: 'Gaming',
		description: `Another layout for Aleris RPG. I don't thinK I used this, though I did like the lightness and textures in it.`,
	},
	{
		id: 22,
		image: `${projectsPath}2013-01-01-mattandadria.jpg`,
		thumb: `${projectsPath}2013-01-01-mattandadria-${thumbnailSize}.jpg`,
		name: 'Matt and Adria',
		date: '01.01.13',
		technologies: 'HTML, CSS, Sass',
		categories: 'Personal',
		description: `Wedding website for myself and my husband. I think this was my fist "single page" website.`,
		url: '//mattandadria.com',
	},
	{
		id: 21,
		image: `${projectsPath}2012-12-01-invalid.jpg`,
		thumb: `${projectsPath}2012-12-01-invalid-${thumbnailSize}.jpg`,
		name: 'Invalid Character Detection',
		date: '12.01.12',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery',
		categories: 'Miscellaneous',
		description: `This tool was build by myself and a friend, Nathan Pennington a long time ago! The date is not accurate. It was meant to take characters and convert them to HTML safe or Unicode conversions. I still use it to this day here and there, though it could use some love at some point.`,
		url: '//neverend.org/invalid',
	},
	{
		id: 20,
		image: `${projectsPath}2012-07-15-aleris.jpg`,
		thumb: `${projectsPath}2012-07-15-aleris-${thumbnailSize}.jpg`,
		name: 'Aleris',
		name2: 'Aleris 2',
		date: '07.15.12',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, phpBB',
		categories: 'Gaming',
		description: `Design for Aleris RPG. I don't think I ever used this as there were a few things I wasn't a fan of.`,
	},
	{
		id: 19,
		image: `${projectsPath}2012-06-04-carol.jpg`,
		thumb: `${projectsPath}2012-06-04-carol-${thumbnailSize}.jpg`,
		name: 'Nutrition Consulting Services',
		date: '06.04.12',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP',
		categories: 'Miscellaneous',
		description: `This one was never fully finished, hence the iStock photo. It was a website for a nutrionist.`,
	},
	{
		id: 18,
		image: `${projectsPath}2012-03-23-colorado-home-base.jpg`,
		thumb: `${projectsPath}2012-03-23-colorado-home-base-${thumbnailSize}.jpg`,
		name: 'Colorado Home Base',
		date: '03.23.12',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP',
		categories: 'Miscellaneous',
		description: `Website for previous real estate agent, Robin Murphy.`,
	},
	{
		id: 17,
		image: `${projectsPath}2011-12-28-muses-circle.jpg`,
		thumb: `${projectsPath}2011-12-28-muses-circle-${thumbnailSize}.jpg`,
		name: 'The Muses Circle',
		date: '12.28.11',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, WordPress',
		categories: 'Journal',
		description: `Blog website for a friend of mine, who reviews books and movies.`,
	},
	{
		id: 16,
		image: `${projectsPath}2011-01-09-aleris.jpg`,
		thumb: `${projectsPath}2011-01-09-aleris-${thumbnailSize}.jpg`,
		name: 'Aleris',
		date: '01.09.11',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP, phpBB',
		categories: 'Gaming',
		description: `First website for Aleris RPG.`,
	},
	{
		id: 15,
		image: `${projectsPath}2010-08-02-federal-mailing.jpg`,
		thumb: `${projectsPath}2010-08-02-federal-mailing-${thumbnailSize}.jpg`,
		name: 'Federal Mailing',
		date: '08.02.10',
		technologies: 'HTML, CSS, Sass, JavaScript, jQuery, PHP',
		categories: 'Miscellaneous',
		description: `Website for a small, mailing business.`,
	},
	{
		id: 14,
		image: `${projectsPath}2009-12-18-matt.jpg`,
		thumb: `${projectsPath}2009-12-18-matt-${thumbnailSize}.jpg`,
		name: 'Matt Murphy Music',
		name2: 'Matt Murphy Music 2',
		date: '12.18.09',
		technologies: 'HTML, CSS, JavaScript, jQuery, PHP',
		categories: 'Miscellaneous',
		description: `Second website for my husband's music. At one point, there was a music player for the songs, but it seems to have broken.`,
		url: '//mattmurphymusic.org',
	},
	{
		id: 13,
		image: `${projectsPath}2009-08-14-portfolio.jpg`,
		thumb: `${projectsPath}2009-08-14-portfolio-${thumbnailSize}.jpg`,
		name: 'Portfolio',
		name2: 'Portfolio 3',
		date: '08.14.09',
		technologies: 'HTML, CSS, JavaScript, jQuery, PHP',
		categories: 'Personal',
		description: `Third portfolio layout. At one point, I think the bright latern in here was animated, because I had big dreams of being able to animate gifs.`,
	},
	{
		id: 12,
		image: `${projectsPath}2009-07-10-portfolio.jpg`,
		thumb: `${projectsPath}2009-07-10-portfolio-${thumbnailSize}.jpg`,
		name: 'Portfolio',
		name2: 'Portfolio 2',
		date: '07.10.09',
		technologies: 'HTML, CSS',
		categories: 'Personal',
		description: `Second portfolio layout. I don't think I actually ever used this, but I was getting into a lot of textures then.`,
	},
	{
		id: 11,
		image: `${projectsPath}2009-05-29-portfolio.jpg`,
		thumb: `${projectsPath}2009-05-29-portfolio-${thumbnailSize}.jpg`,
		name: 'Portfolio',
		date: '05.29.09',
		technologies: 'HTML, CSS',
		categories: 'Personal',
		description: `First portfolio layout.`,
	},
	{
		id: 10,
		image: `${projectsPath}2007-04-28-ro-diary.jpg`,
		thumb: `${projectsPath}2007-04-28-ro-diary-${thumbnailSize}.jpg`,
		name: 'RO Diary',
		name2: 'RO Diary 2',
		date: '04.28.07',
		technologies: 'HTML, CSS',
		categories: 'Journal',
		description: `Last RO Diary layout. I don't think I lasted long on there.`,
	},
	{
		id: 9,
		image: `${projectsPath}2007-03-02-neverend.jpg`,
		thumb: `${projectsPath}2007-03-02-neverend-${thumbnailSize}.jpg`,
		name: 'Neverend',
		name2: 'Neverend 5',
		date: '03.02.07',
		technologies: 'HTML, CSS',
		categories: 'Gaming',
		description: `Website for my Ragnarok Online guild, Neverend.`,
	},
	{
		id: 8,
		image: `${projectsPath}2006-11-26-neverend.jpg`,
		thumb: `${projectsPath}2006-11-26-neverend-${thumbnailSize}.jpg`,
		name: 'Neverend',
		name2: 'Neverend 4',
		date: '11.26.06',
		technologies: 'HTML, CSS',
		categories: 'Gaming',
		description: `Website for my Ragnarok Online guild, Neverend.`,
	},
	{
		id: 7,
		image: `${projectsPath}2006-11-16-ro-diary.jpg`,
		thumb: `${projectsPath}2006-11-16-ro-diary-${thumbnailSize}.jpg`,
		name: 'RO Diary',
		date: '11.16.06',
		technologies: 'HTML, CSS',
		categories: 'Journal',
		description: `Back in the day, some one created this spin off of diaries for Ragnarok Online. Kinda like LiveJournal, but for Ragnarok Online so you can rant about card drop rates.`,
	},
	{
		id: 6,
		image: `${projectsPath}2006-07-06-matt.jpg`,
		thumb: `${projectsPath}2006-07-06-matt-${thumbnailSize}.jpg`,
		name: 'Matt Murphy Music',
		date: '07.06.06',
		technologies: 'HTML, CSS',
		categories: 'Miscellaneous',
		description: `First music website for my husband. I don't know if I actually ever built this out.`,
	},
	{
		id: 5,
		image: `${projectsPath}2006-06-07-neverend.jpg`,
		thumb: `${projectsPath}2006-06-07-neverend-${thumbnailSize}.jpg`,
		name: 'Neverend',
		name2: 'Neverend 3',
		date: '06.07.06',
		technologies: 'HTML, CSS',
		categories: 'Gaming',
		description: `Website for my Ragnarok Online guild, Neverend.`,
	},
	{
		id: 4,
		image: `${projectsPath}2006-02-04-neverend.jpg`,
		thumb: `${projectsPath}2006-02-04-neverend-${thumbnailSize}.jpg`,
		name: 'Neverend',
		name2: 'Neverend 2',
		date: '02.04.06',
		technologies: 'HTML, CSS',
		categories: 'Gaming',
		description: `Website for my Ragnarok Online guild, Neverend.`,
	},
	{
		id: 3,
		image: `${projectsPath}2005-12-19-be-careful.jpg`,
		thumb: `${projectsPath}2005-12-19-be-careful-${thumbnailSize}.jpg`,
		name: 'Be Careful',
		date: '12.19.05',
		technologies: 'HTML, CSS',
		categories: 'Miscellaneous',
		description: `Website for a Care Bear Cousins fanlisting, back when fanlistings were a thing and super popular. I liked my clever use of the "Be Careful" website name.`,
	},
	{
		id: 2,
		image: `${projectsPath}2005-06-18-neverend.jpg`,
		thumb: `${projectsPath}2005-06-18-neverend-${thumbnailSize}.jpg`,
		name: 'Neverend',
		date: '06.18.05',
		technologies: 'HTML, CSS',
		categories: 'Gaming',
		description: `Website for my Ragnarok Online guild, Neverend.`,
	},
	{
		id: 1,
		image: `${projectsPath}2005-05-09-terrae.jpg`,
		thumb: `${projectsPath}2005-05-09-terrae-${thumbnailSize}.jpg`,
		name: 'Terrae',
		date: '05.09.05',
		technologies: 'HTML, CSS',
		categories: 'Personal',
		description: `First iteration of a website for a story I want to write... some day.`,
	},
	{
		id: 0,
		image: `${projectsPath}2004-08-20-oneiro.jpg`,
		thumb: `${projectsPath}2004-08-20-oneiro-${thumbnailSize}.jpg`,
		name: 'Oneiro-Zoe',
		date: '08.20.04',
		technologies: 'HTML, CSS',
		categories: 'Gaming',
		description: `Not my very first design, but a quick website for an RPG.`,
	},
];
