const distPath = '/assets/images/';
const artPath = `${distPath}art/`;

export let art = [
	{
		id: 71,
		image: `${artPath}2025-01-20-theme-icons.png`,
		thumb: `${artPath}2025-01-20-theme-icons-34x34.png`,
		name: 'Theme Icons',
		date: '01.20.25',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Social media icons I made for this portfolio. I first made the icons in a brown color scale to match the site colors, then switched to brand colors.`,
	},
	{
		id: 70,
		image: `${artPath}2022-11-20-ff7-materia.png`,
		thumb: `${artPath}2022-11-20-ff7-materia.png`,
		name: 'Support Materia',
		date: '11.20.22',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `A blue support materia, which is used for the <a href="//ff7forstjude.org" target="_blank" rel="noreferrer">FF7 for St. Jude</a> page as the favicon.`,
	},
	{
		id: 69,
		image: `${artPath}2021-12-04-toastmatt-sad-bread.png`,
		thumb: `${artPath}2021-12-04-toastmatt-sad-bread.png`,
		name: 'Sad Bread',
		date: '12.04.21',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Does a sad bread make itself soggy? For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 68,
		image: `${artPath}2021-12-04-toastmatt-materia-bread.png`,
		thumb: `${artPath}2021-12-04-toastmatt-materia-bread.png`,
		name: 'Materia Bread',
		date: '12.04.21',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `I kinda hate this one, lol, but it's bread with materia slots. For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 67,
		image: `${artPath}2021-11-28-money-bread.gif`,
		thumb: `${artPath}2021-11-28-money-bread.gif`,
		name: 'Money Bread',
		date: '11.28.21',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Currency with a bread icon. It's even animated! For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 66,
		image: `${artPath}2021-11-26-toastmatt-rip-bread.png`,
		thumb: `${artPath}2021-11-26-toastmatt-rip-bread.png`,
		name: 'RIP Bread',
		date: '11.26.21',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Okay, it's not really bread, but a tombstone shaped like bread. I felt kinda clever. For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 65,
		image: `${artPath}2021-11-26-toastmatt-mad-bread.png`,
		thumb: `${artPath}2021-11-26-toastmatt-mad-bread.png`,
		name: 'Mad Breads',
		date: '11.26.21',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `The bread is back and this one is mad. For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 64,
		image: `${artPath}2021-03-13-khyeras-heart-badge.png`,
		thumb: `${artPath}2021-03-13-khyeras-heart-badge.png`,
		name: 'Heart Badge',
		date: '03.13.21',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `A heart badge for a Valentine's Day writing prompt event at <a href="//khyeras.org" target="_blank" rel="noreferrer">Khy'eras</a>.`,
	},
	{
		id: 63,
		image: `${artPath}2020-12-20-displaycofee-wave.png`,
		thumb: `${artPath}2020-12-20-displaycofee-wave.png`,
		name: 'Wave',
		date: '12.20.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Feena from "Grandia" doing a little wave. For my <a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">channel</a>.`,
	},
	{
		id: 62,
		image: `${artPath}2020-12-20-displaycofee-hmm.png`,
		thumb: `${artPath}2020-12-20-displaycofee-hmm.png`,
		name: 'Hmmm',
		date: '12.20.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Alundra from "Alundra" thinking about puzzles. For my <a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">channel</a>.`,
	},
	{
		id: 61,
		image: `${artPath}2020-12-20-displaycofee-charge.png`,
		thumb: `${artPath}2020-12-20-displaycofee-charge.png`,
		name: 'Charge',
		date: '12.20.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Frog from "Chrono Trigger" for my <a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">channel</a>.`,
	},
	{
		id: 60,
		image: `${artPath}2020-10-25-khyeras-pumpkin-badge.png`,
		thumb: `${artPath}2020-10-25-khyeras-pumpkin-badge.png`,
		name: 'Pumpkin Badge',
		date: '10.25.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `A pumpkin badge for a Halloween writing prompt event at <a href="//khyeras.org" target="_blank" rel="noreferrer">Khy'eras</a>.`,
	},
	{
		id: 59,
		image: `${artPath}2020-08-24-displaycofee-hello.png`,
		thumb: `${artPath}2020-08-24-displaycofee-hello.png`,
		name: 'Hello',
		date: '08.24.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `I created this for my <a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">channel</a>, but ended up removing it. It's Toothless from "How to Train Your Dragon" waving.`,
	},
	{
		id: 58,
		image: `${artPath}2020-07-25-chestermcfisty-git-gud.png`,
		thumb: `${artPath}2020-07-25-chestermcfisty-git-gud.png`,
		name: 'Git Gud',
		date: '07.25.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Also known as "get good". For <a href="//twitch.tv/chestermcfisty" target="_blank" rel="noreferrer">chestermcfisty</a>.`,
	},
	{
		id: 57,
		image: `${artPath}2020-07-19-scubasaul-pineapple.png`,
		thumb: `${artPath}2020-07-19-scubasaul-pineapple.png`,
		name: 'No Hints Please',
		date: '07.19.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `<a href="//twitch.tv/scubasaul" target="_blank" rel="noreferrer">scubasaul</a>'s safe word to get a hint in a game is "pineapple", so I made him a not-so-impressed Terminator pineapple.`,
	},
	{
		id: 56,
		image: `${artPath}2020-07-12-displaycofee-coffee-bean.png`,
		thumb: `${artPath}2020-07-12-displaycofee-coffee-bean.png`,
		name: 'Coffee Bean',
		date: '07.12.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `A coffee bean used for the channel point icon on my <a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">channel</a>.`,
	},
	{
		id: 55,
		image: `${artPath}2020-07-11-displaycoffee-red-mug.png`,
		thumb: `${artPath}2020-07-11-displaycoffee-red-mug.png`,
		name: 'Red Coffee Mug',
		date: '07.11.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `<a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">My</a> sub-badge of a red coffee mug with a paw print.`,
	},
	{
		id: 54,
		image: `${artPath}2020-07-11-displaycoffee-purple-mug.png`,
		thumb: `${artPath}2020-07-11-displaycoffee-purple-mug.png`,
		name: 'Purple Coffee Mug',
		date: '07.11.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `<a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">My</a> sub-badge of a purple coffee mug with a starburst (not the candy).`,
	},
	{
		id: 53,
		image: `${artPath}2020-07-11-displaycoffee-orange-mug.png`,
		thumb: `${artPath}2020-07-11-displaycoffee-orange-mug.png`,
		name: 'Orange Coffee Mug',
		date: '07.11.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `<a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">My</a> sub-badge of a orange coffee mug with a crescent moon.`,
	},
	{
		id: 52,
		image: `${artPath}2020-07-11-displaycoffee-green-mug.png`,
		thumb: `${artPath}2020-07-11-displaycoffee-green-mug.png`,
		name: 'Green Coffee Mug',
		date: '07.11.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `<a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">My</a> sub-badge of a green coffee mug with a swirl.`,
	},
	{
		id: 51,
		image: `${artPath}2020-07-11-displaycoffee-blue-mug.png`,
		thumb: `${artPath}2020-07-11-displaycoffee-blue-mug.png`,
		name: 'Blue Coffee Mug',
		date: '07.11.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `<a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">My</a> sub-badge of a blue coffee mug with a heart.`,
	},
	{
		id: 50,
		image: `${artPath}2020-07-11-displaycofee-love.png`,
		thumb: `${artPath}2020-07-11-displaycofee-love.png`,
		name: 'Vivi Love',
		date: '07.11.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Vivi from Final Fantasy IX. For my <a href="//twitch.tv/displaycoffee" target="_blank" rel="noreferrer">channel</a>.`,
	},
	{
		id: 49,
		image: `${artPath}2020-07-05-novakatebs-medkit.png`,
		thumb: `${artPath}2020-07-05-novakatebs-medkit.png`,
		name: 'Support',
		date: '07.05.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `A medkit for all those viewers that support <a href="//twitch.tv/novakatebs" target="_blank" rel="noreferrer">novakatebs</a>.`,
	},
	{
		id: 48,
		image: `${artPath}2020-07-05-chestermcfisty-ggez.png`,
		thumb: `${artPath}2020-07-05-chestermcfisty-ggez.png`,
		name: 'GGEZ',
		date: '07.05.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Gold knuckles with GGEZ. I think that's "good game easy" for all you hip youngesters out there. For <a href="//twitch.tv/chestermcfisty" target="_blank" rel="noreferrer">chestermcfisty</a>.`,
	},
	{
		id: 47,
		image: `${artPath}2020-07-04-savko-tilt.png`,
		thumb: `${artPath}2020-07-04-savko-tilt.png`,
		name: 'Tilt',
		date: '07.04.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `An enraged, tilted <a href="//twitch.tv/savko" target="_blank" rel="noreferrer">savko</a>.`,
	},
	{
		id: 46,
		image: `${artPath}2020-07-04-savko-platforming.png`,
		thumb: `${artPath}2020-07-04-savko-platforming.png`,
		name: 'Platforming Bad',
		date: '07.04.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `An attempt at platforming for <a href="//twitch.tv/savko" target="_blank" rel="noreferrer">savko</a> as there's always some sort of fail.`,
	},
	{
		id: 45,
		image: `${artPath}2020-07-04-savko-greed.png`,
		thumb: `${artPath}2020-07-04-savko-greed.png`,
		name: 'Greed',
		date: '07.04.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `One of my favorite RPG / fantasy monsters, the mimic. For <a href="//twitch.tv/savko" target="_blank" rel="noreferrer">savko</a>.`,
	},
	{
		id: 44,
		image: `${artPath}2020-07-03-savko-lore.png`,
		thumb: `${artPath}2020-07-03-savko-lore.png`,
		name: 'Lore',
		date: '07.03.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Made for <a href="//twitch.tv/savko" target="_blank" rel="noreferrer">savko</a> as he always has the coolest stories to tell.`,
	},
	{
		id: 43,
		image: `${artPath}2020-07-03-savko-kwr.png`,
		thumb: `${artPath}2020-07-03-savko-kwr.png`,
		name: 'Kate Was Right',
		date: '07.03.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Was Kate right? According to <a href="//twitch.tv/savko" target="_blank" rel="noreferrer">savko</a> she was, so we gave her a little crown.`,
	},
	{
		id: 42,
		image: `${artPath}2020-06-06-toastmatt-wave-bread.png`,
		thumb: `${artPath}2020-06-06-toastmatt-wave-bread.png`,
		name: 'Wave Bread',
		date: '06.06.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Just bread saying hello. For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 41,
		image: `${artPath}2020-06-06-toastmatt-gold-bread.png`,
		thumb: `${artPath}2020-06-06-toastmatt-gold-bread.png`,
		name: 'Gold',
		date: '06.06.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `That's some shiny bread. Probably doesn't taste good. For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 40,
		image: `${artPath}2020-05-24-toastmatt-pb-bread.png`,
		thumb: `${artPath}2020-05-24-toastmatt-pb-bread.png`,
		name: 'PB Bread',
		date: '05.24.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Peanut butter or personal best? The choice is yours and yours alone.`,
	},
	{
		id: 39,
		image: `${artPath}2020-05-23-toastmatt-smile-bread.png`,
		thumb: `${artPath}2020-05-23-toastmatt-smile-bread.png`,
		name: 'Smile Bread',
		date: '05.23.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Smile. &#128512; For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 38,
		image: `${artPath}2020-05-23-toastmatt-love-bread.png`,
		thumb: `${artPath}2020-05-23-toastmatt-love-bread.png`,
		name: 'Love Bead',
		date: '05.23.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `This bread is in love. <3 For <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 37,
		image: `${artPath}2020-05-07-toastmatt-well-done.png`,
		thumb: `${artPath}2020-05-07-toastmatt-well-done.png`,
		name: 'Well Done',
		date: '05.07.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Well done toast for <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 36,
		image: `${artPath}2020-04-30-toatmatt-bread-badges.png`,
		thumb: `${artPath}2020-04-30-toatmatt-bread-badges-18x18.png`,
		name: 'Bread Badges',
		date: '04.30.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Bread sub-badges for <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>. We didn't use all of these, but the gradient is cool.`,
	},
	{
		id: 35,
		image: `${artPath}2020-04-30-toastmatt-dead-bread.png`,
		thumb: `${artPath}2020-04-30-toastmatt-dead-bread.png`,
		name: 'Dead Bread',
		date: '04.30.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `Dead Bread for <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>. Reminds us of the Nirvana smiley face, most likely inspired by it.`,
	},
	{
		id: 34,
		image: `${artPath}2020-04-17-toastmatt-soft-lock.png`,
		thumb: `${artPath}2020-04-17-toastmatt-soft-lock.png`,
		name: 'Soft Lock',
		date: '04.17.20',
		mediums: 'Aseprite',
		categories: 'Pixels',
		description: `My first twitch emote for <a href="//twitch.tv/toast_matt" target="_blank" rel="noreferrer">toast_matt</a>.`,
	},
	{
		id: 33,
		image: `${artPath}2019-12-12-khyeras-map.jpg`,
		thumb: `${artPath}2019-12-12-khyeras-map-200x200.jpg`,
		name: `Khy'eras Map`,
		date: '12.12.19',
		mediums: 'Photoshop',
		categories: 'Digital',
		description: `My second attempt at making a map, for Khy'eras, and a much improved version. This is an interactive version of the map <a href="//khyeras.org/setting-map" target="_blank" rel="noreferrer">found here</a>.`,
	},
	{
		id: 32,
		image: `${artPath}2013-03-23-charlie-rabbit.jpg`,
		thumb: `${artPath}2013-03-23-charlie-rabbit-200x200.jpg`,
		name: 'Charlie Rabbit',
		date: '03.23.13',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `A marionette named Charlie Rabbit. This was based on my husband's song, Charlie Rabbit, and later we used it for his album cover.`,
	},
	{
		id: 31,
		image: `${artPath}2012-12-01-aleris-map.jpg`,
		thumb: `${artPath}2012-12-01-aleris-map-200x200.jpg`,
		name: 'Aleris Map',
		date: '12.01.12',
		mediums: 'Photoshop',
		categories: 'Digital',
		description: `One of my first attempts at map making for my RPG Aleris.`,
	},
	{
		id: 30,
		image: `${artPath}2011-02-14-beatrix.jpg`,
		thumb: `${artPath}2011-02-14-beatrix-200x200.jpg`,
		name: 'Beatrix',
		date: '02.14.11',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `I drew this for my husband, but we both love the character Beatrix from Final Fantasy IX.`,
	},
	{
		id: 29,
		image: `${artPath}2008-12-21-pachico.jpg`,
		thumb: `${artPath}2008-12-21-pachico-200x200.jpg`,
		name: 'Pachico',
		date: '12.21.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `Pachico, a friend's mastersmith from Ragnarok Online.`,
	},
	{
		id: 28,
		image: `${artPath}2008-08-03-cantrixe.jpg`,
		thumb: `${artPath}2008-08-03-cantrixe-200x200.jpg`,
		name: 'Cantrixe',
		date: '08.03.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `A punked/gothed out version of Ragnarok Online high priestess, Cantrixe`,
	},
	{
		id: 27,
		image: `${artPath}2008-05-24-levanth.jpg`,
		thumb: `${artPath}2008-05-24-levanth-200x200.jpg`,
		name: 'Levanth',
		date: '05.24.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `Levanth the paladin from Ragnarok Online. I like a man in armor and kitty ears.`,
	},
	{
		id: 26,
		image: `${artPath}2008-05-20-yours-truly.jpg`,
		thumb: `${artPath}2008-05-20-yours-truly-200x200.jpg`,
		name: 'Yours Truly',
		date: '05.20.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `My Ragnarok Online sage named Yours Truly. The name was stolen from "Snow Crash" by Neal Stephenson.`,
	},
	{
		id: 25,
		image: `${artPath}2008-04-12-eleotea.jpg`,
		thumb: `${artPath}2008-04-12-eleotea-200x200.jpg`,
		name: 'Eleotea',
		date: '04.12.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `A goth-style battle high priestess named Eleotea. From, you guessed it, Ragnarok Online. I did some coloring here with my tablet for once, which I was never great at.`,
	},
	{
		id: 24,
		image: `${artPath}2008-03-01-sol.jpg`,
		thumb: `${artPath}2008-03-01-sol-200x200.jpg`,
		name: 'Sol',
		date: '03.01.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `Sol the high priest (from Ragnarok Online) lovingly caressing his long braid.`,
	},
	{
		id: 23,
		image: `${artPath}2008-02-22-melody.jpg`,
		thumb: `${artPath}2008-02-22-melody-200x200.jpg`,
		name: 'Melody',
		date: '02.22.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `Melody, a Ragnarok Online dancer.`,
	},
	{
		id: 22,
		image: `${artPath}2008-02-16-harpe.jpg`,
		thumb: `${artPath}2008-02-16-harpe-200x200.jpg`,
		name: 'Harpe',
		date: '02.16.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `I believe this was a ninja named, Harpe, in Ragnarok Online.`,
	},
	{
		id: 21,
		image: `${artPath}2008-02-11-pachico.jpg`,
		thumb: `${artPath}2008-02-11-pachico-200x200.jpg`,
		name: 'Pachico',
		date: '02.11.08',
		mediums: 'Wacom tablet, Photoshop',
		categories: 'Digital',
		description: `Pachico, a friend's mastersmith from Ragnarok Online.`,
	},
	{
		id: 20,
		image: `${artPath}2007-07-31-docks.jpg`,
		thumb: `${artPath}2007-07-31-docks-200x200.jpg`,
		name: 'Emfei Fien Docks',
		date: '07.31.07',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `Tempest sitting on the docks of his hometown, Emfei Fien.`,
	},
	{
		id: 19,
		image: `${artPath}2007-05-05-heart-umbrella.jpg`,
		thumb: `${artPath}2007-05-05-heart-umbrella-200x200.jpg`,
		name: 'Heart Umbrella',
		date: '05.05.07',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `I kinda liked drawing umbrellas, so this is my husband's high priest and my assassin cross from Ragnarok Online.`,
	},
	{
		id: 18,
		image: `${artPath}2007-04-13-kyra-jazzy.jpg`,
		thumb: `${artPath}2007-04-13-kyra-jazzy-200x200.jpg`,
		name: 'Kyra Darkblood and Jazzy',
		date: '04.13.07',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `Two wizards from Ragnarok Online; one of these wizard's belonged to Kyra Darkblood.`,
	},
	{
		id: 17,
		image: `${artPath}2007-03-16-caiin.jpg`,
		thumb: `${artPath}2007-03-16-caiin-200x200.jpg`,
		name: 'Caiin',
		date: '03.16.07',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `A Ragnarok Online priestess with her drooping kitty, both decked out to be thug-like. I called her "Caiin" one day do to my fat-fingered typing.`,
	},
	{
		id: 16,
		image: `${artPath}2006-10-02-rhio-tempest.jpg`,
		thumb: `${artPath}2006-10-02-rhio-tempest-200x200.jpg`,
		name: 'Rhio and Tempest',
		date: '10.02.06',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `This is a re-do of the previous drawing as I wasn't too fond of the colors. I wanted them to be a little more nuetral.`,
	},
	{
		id: 15,
		image: `${artPath}2005-11-02-nightmare.jpg`,
		thumb: `${artPath}2005-11-02-nightmare-200x200.jpg`,
		name: '"N" is for "Nightmare"',
		date: '11.02.05',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `I'm unsure of the exact date on this, but it was an art school project where we had to draw the letters of the alphabet, but make them represent a concept.`,
	},
	{
		id: 14,
		image: `${artPath}2005-10-28-kyra.jpg`,
		thumb: `${artPath}2005-10-28-kyra-200x200.jpg`,
		name: 'Kyra Darkblood',
		date: '10.28.05',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `Ragnarok Online priestess named Kyra Darkblood.`,
	},
	{
		id: 13,
		image: `${artPath}2005-10-12-slash-kis.jpg`,
		thumb: `${artPath}2005-10-12-slash-kis-200x200.jpg`,
		name: '/kis',
		date: '10.12.05',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `My Ragnarok Online assassin (Kaila) and my husband's prest (Iezu). Doin' a little /kis command.`,
	},
	{
		id: 12,
		image: `${artPath}2005-09-30-reid.jpg`,
		thumb: `${artPath}2005-09-30-reid-200x200.jpg`,
		name: 'Reid Feral',
		date: '09.30.05',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `My roleplaying character, Reid Feral.`,
	},
	{
		id: 11,
		image: `${artPath}2005-09-16-manaeros.jpg`,
		thumb: `${artPath}2005-09-16-manaeros-200x200.jpg`,
		name: 'Manaeros',
		date: '09.16.05',
		mediums: 'Pen',
		categories: 'Traditional',
		description: `Messy sketch of an angel type race in Terrae.`,
	},
	{
		id: 10,
		image: `${artPath}2005-08-21-wait-for-me.jpg`,
		thumb: `${artPath}2005-08-21-wait-for-me-200x200.jpg`,
		name: 'Wait for Me',
		date: '08.21.05',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `Inspire by a song my husband wrote, features me and my husband in the rain under the cutest star umbrella.`,
	},
	{
		id: 9,
		image: `${artPath}2005-04-06-cantrixe.jpg`,
		thumb: `${artPath}2005-04-06-cantrixe-200x200.jpg`,
		name: 'Cantrixe',
		date: '04.06.05',
		mediums: 'Pen',
		categories: 'Traditional',
		description: `Pen sketch of a Ragnarok Online priestess named Cantrixe.`,
	},
	{
		id: 8,
		image: `${artPath}2005-01-14-rhio-tempest.jpg`,
		thumb: `${artPath}2005-01-14-rhio-tempest-200x200.jpg`,
		name: 'Rhio and Tempest',
		date: '01.14.05',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `Characters (Rhio and Tempest) from a story called Terrae. I might write it some day.`,
	},
	{
		id: 7,
		image: `${artPath}2004-10-13-kiska.jpg`,
		thumb: `${artPath}2004-10-13-kiska-200x200.jpg`,
		name: 'Kiska',
		date: '10.13.04',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `Kiska, a hunter from Ragnarok Online.`,
	},
	{
		id: 6,
		image: `${artPath}2004-10-13-kaila.jpg`,
		thumb: `${artPath}2004-10-13-kaila-200x200.jpg`,
		name: 'Kaila',
		date: '10.13.04',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `My Ragnarok Online assassin, Kaila.`,
	},
	{
		id: 5,
		image: `${artPath}2004-02-24-kaila-zomba.jpg`,
		thumb: `${artPath}2004-02-24-kaila-zomba-200x200.jpg`,
		name: 'Kaila and Zomba',
		date: '02.24.04',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `My Ragnarok Online assassin, Kaila, and her pet spore, Zomba.`,
	},
	{
		id: 4,
		image: `${artPath}2003-06-09-never-falling.jpg`,
		thumb: `${artPath}2003-06-09-never-falling-200x200.jpg`,
		name: 'Never Falling',
		date: '06.09.03',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `My RPG character and his wife, Necia`,
	},
	{
		id: 3,
		image: `${artPath}2003-01-23-reid.jpg`,
		thumb: `${artPath}2003-01-23-reid-200x200.jpg`,
		name: 'Reid Feral',
		date: '01.23.03',
		mediums: 'Watercolor, colored pencil, pen',
		categories: 'Traditional',
		description: `My roleplaying character, Reid Feral.`,
	},
	{
		id: 2,
		image: `${artPath}2003-01-11-flower.jpg`,
		thumb: `${artPath}2003-01-11-flower-200x200.jpg`,
		name: `I'll Miss You`,
		date: '01.11.03',
		mediums: 'Pen',
		categories: 'Traditional',
		description: `Pen sketch of a character (Tempest) from a story of mine.`,
	},
	{
		id: 1,
		image: `${artPath}2002-10-23-verial-sorvynia.jpg`,
		thumb: `${artPath}2002-10-23-verial-sorvynia-200x200.jpg`,
		name: 'Verial and Sorvynia',
		date: '10.23.02',
		mediums: 'Pencil',
		categories: 'Traditional',
		description: `My RPG character as a kid and his mom, Sorvynia.`,
	},
	{
		id: 0,
		image: `${artPath}2002-10-23-verial-necia.jpg`,
		thumb: `${artPath}2002-10-23-verial-necia-200x200.jpg`,
		name: 'Verial and Necia',
		date: '10.23.02',
		mediums: 'Pencil',
		categories: 'Traditional',
		description: `My RPG character and his wife, Necia.`,
	},
];
