export const resume = {
	technical: {
		languages: [
			{
				id: 8,
				name: 'HTML',
				value: 9,
			},
			{
				id: 7,
				name: 'CSS',
				value: 9,
			},
			{
				id: 6,
				name: 'Sass',
				value: 9,
			},
			{
				id: 5,
				name: 'JavaScript',
				value: 9,
			},
			{
				id: 4,
				name: 'React',
				value: 8,
			},
			{
				id: 3,
				name: 'TypeScript',
				value: 5,
			},
			{
				id: 2,
				name: 'Angular',
				value: 6,
			},
			{
				id: 1,
				name: 'PHP',
				value: 7,
			},
			{
				id: 0,
				name: 'jQuery',
				value: 8,
			},
		],
		cms: 'WordPress, WHMCS, phpBB, eCommerce platforms (Shopify, BigCommerce, Magento2, etc.)',
		tools: 'Git, Vite, Webpack, GraphQL, Rest APIs, Cypress, Lighthouse, TanStack Query, ESLint',
		other: 'Experienced with major web browsers, Windows, MacOS, VSCode, Chrome Dev Tools',
	},
	history: [
		{
			id: 4,
			name: 'Searchspring',
			role: 'Senior Frontend Engineer and Team Lead',
			date: 'November 2014 to <strong>Current</strong>',
			description: [
				`Engineered complex integrations using proprietary APIs/SDKs to build real-time search and discovery experiences for major global eCommerce brands`,
				`Created mockups to demo product features when integrated on a client's eCommerce website`,
				`Developed internal scaffolds (component libraries and templates) using Sass and React, reducing project implementation time`,
				`Architected customer-facing "Snap Templates" using React, TypeScript, and CSS-in-JS (Emotion), enabling clients to build custom, high-conversion frontend experiences via modular themes`,
				`Defined QA processes and participated in QAs (self and peer) before work is handed off to client`,
				`Wrote customer-facing Knowledge Base articles, internal team documentation, and code snippets`,
				`Led a Frontend engineering team, defining best practices for code quality, performance, and accessibility across the Professional Services organization`,
				`Spearheaded the technical scoping for custom client requirements, directly contributing to regional revenue growth`,
				`Utilized Cypress and Lighthouse testing to automate certain checks before merging GitHub branches into production`,
				`Participated in "Early Access" programs to help develop and test new products`,
				`Prior to open PTO policy, advocated for "Volunteer Time Off" which was approved and allowed for 16 separate hours devoted to volunteer work`,
				`Helped to plan and advocate for the first Implementations Team Meet-up in 2023`,
				`HTML, CSS, Sass, JavaScript, JavaScript frameworks (jQuery, React, Angular), Git, TypeScript, CSS-in-JS`,
			],
		},
		{
			id: 3,
			name: 'Power Plant Media',
			role: 'Frontend Web Developer',
			date: 'October 2013 to September 2014',
			description: [
				`Developed mobile-first, responsive WordPress and WooCommerce themes from scratch, focusing on speed and conversion`,
				`Coded HTML email newsletters`,
				`Built templates and themes for WordPress, WooCommerce, and WHMCS`,
				`Created custom PHP plugins and content types to extend CMS functionality`,
				`Implemented Schema.org markup and rich snippets to improve organic search visibility and click-through rates`,
				`Performed cross-browser device testing`,
				`HTML, CSS, Sass, Compass, PHP, JavaScript, jQuery, Photoshop`,
			],
		},
		{
			id: 2,
			name: 'Decentrix Inc.',
			role: 'Graphic Designer and Frontend Web Developer',
			date: 'April 2013 to September 2013',
			description: [
				`Designed and implemented website customizations for DISH authorized retailers`,
				`Modernized legacy codebases to meet current web standards, improving cross-browser compatibility and page load speeds`,
				`Performed daily maintenance on pages to keep code current with web standards as well as concise, simple, and effective`,
				`Created graphic design for banners, home page sliders, image sprites, and buttons`,
				`Wrote and proofread content for the web when necessary`,
				`HTML, CSS, JavaScript, jQuery, Photoshop, IntelliJ IDEA, Microsoft Office`,
			],
		},
		{
			id: 1,
			name: 'AT&T',
			role: 'Implementation Specialist',
			date: 'April 2010 to April 2013',
			description: [
				`Reviewed and analyzed project documents used to place content on att.com (logging and solving issues as a result)`,
				`Implemented content using TeamSite and thoroughly checked each piece of content for errors in the process`,
				`Participated in various clean-up efforts (reviewing files in TeamSite and website scrubs)`,
				`Created new tools (JavaScript HTML character translator and invalid character checker)`,
				`Involved in testing of new tools within AT&T`,
				`QAed implementation work of team members`,
				`HTML, CSS, JavaScript, TeamSite, Microsoft Office, Wiki, SharePoint`,
			],
		},
		{
			id: 0,
			name: 'Hilton Worldwide',
			role: 'Web Analyst',
			date: 'November 2007 to April 2010',
			description: [
				`Created special offers on hotel websites across all Hilton Worldwide brands (includes daily copywriting, proofreading, and HTML editing)`,
				`Reviewed and published promotion built for brand websites (Hilton.com, Doubletreee.com, etc.)`,
				`Edited images and content for the web using CMS (TeamSite and MediaBin)`,
				`Placed on various projects - Hampton Focus, imagery clean up, Trade Show attendance`,
				`HTML, CSS, JavaScript, Photoshop, Interwoven / TeamSite, MediaBin, Microsoft Office`,
			],
		},
	],
	volunteer: [
		{
			id: 2,
			name: 'FF7 for St. Jude',
			date: 'December 2020 to Current',
			description: [
				`Assisted in organizing and managing a global charity event where Final Fantasy VII speed runners get together to raise money for St. Jude Children's Research Hospital`,
				`Architected a real-time React dashboard for the event, integrating the Tiltify API to visualize live donation data and event milestones for thousands of concurrent users`,
				`To date, we have raised $53,607.61 for St. Jude`,
			],
		},
		{
			id: 1,
			name: 'Girls in Tech - Colorado Springs',
			date: 'November 2019 to November 2020',
			description: [`Helped start Colorado Springs Girls in Tech chapter and first event`, `Performed website updates for the chapter`],
		},
		{
			id: 0,
			name: 'BarkaBull Dog Rescue',
			date: 'October 2018 to March 2019',
			description: [`Fostered dogs until they were ready for adoption`, `Cared for dogs by providing daily essential and medical needs`],
		},
	],
};
